<?php

/**
 * @file
 * An implementation of timelineJS http://timeline.verite.co/
 */

 function timelinejs_admin() {
   $form = array();

   $form['timelinejs_source'] = array(
    '#type' => 'textfield',
    '#title' => t('Timeline source'),
    '#default_value' => variable_get('timelinejs_source', ''),
    '#size' => 100,
    '#description' => t('The source of your timeline'),
    '#required' => TRUE,
   );

   return system_settings_form($form);
 }


function timelinejs_menu() {

  $items = array();

  $items['admin/config/services/timelinejs'] = array(
    'title' => 'Timelinejs module settings',
    'description' => t('Settings for your timeline'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('timelinejs_admin'),
    'access arguments' => array('administer timelinejs settings'),
    'type' => MENU_NORMAL_ITEM,
   );

  return $items;
}

drupal_add_js(base_path()."sites/all/modules/custom/timelinejs/timeline_embed.js", "file");



