<?php

/**
 * @file
 * An implementation of timelineJS http://timeline.verite.co/
 */

 function timelinejs_admin() {
   $form = array();

   $form['timelinejs_source'] = array(
    '#type' => 'textfield',
    '#title' => t('Timeline source'),
    '#default_value' => variable_get('timelinejs_source', ''),
    '#size' => 100,
    '#description' => t('The source of your timeline'),
    '#required' => TRUE,
   );

   return system_settings_form($form);
 }


function timelinejs_menu() {

  $items = array();

  $items['admin/config/services/timelinejs'] = array(
    'title' => 'Timelinejs module settings',
    'description' => t('Settings for your timeline'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('timelinejs_admin'),
    'access arguments' => array('administer timelinejs settings'),
    'type' => MENU_NORMAL_ITEM,
   );

  return $items;
}

function timelinejs_node_load($nodes, $types) {
  if ($nodes[2]->type == "article") {

    drupal_add_js(array('timelinejs' => array(
      'embedSource' => "<script type='text/javascript' src='".$GLOBALS['base_url']."/sites/all/modules/custom/timelinejs/TimelineJS/compiled/js/storyjs-embed.js'></script>",
      )), array('type' => 'setting', 'weight' => 10));

    drupal_add_js(base_path()."sites/all/modules/custom/timelinejs/timeline_embed.js", array('type' => 'file', 'weight' => 0));

    #drupal_add_js(base_path
  }
}

/** 
 * Implements hook_node_view()
 */

function timelinejs_node_view($node, $view_mode, $langcode) {
  if ($node->field_include_timeline_['und'][0]['value'] != 1) {
    return;
  }

  $node->content['timelinejs_timeline'] = array(
    '#type' => 'item',
    '#title' => t('timeline'),
    '#markup' => '<div id="timeline-embed"></div>',
    );
}

/**
 * Implements hook_field_extra_fields()
 */

function timelinejs_field_extra_fields() {
  $extra['node']['article']['display'] = array(
    'timelinejs_timeline' => array(
      'label' => t('My Timelinejs'),
      'description' => t('A timeline made from Timelinejs'),
      'weight' => 10,
      ),
  );
  return $extra;
}




