<?php

/**
 * @file
 * An implementation of timelineJS http://timeline.verite.co/
 */

 function timelinejs_admin() {
   $form = array();

   $form['timelinejs_source'] = array(
    '#type' => 'textfield',
    '#title' => t('Timeline source'),
    '#default_value' => variable_get('timelinejs_source', ''),
    '#size' => 100,
    '#description' => t('The source of your timeline'),
    '#required' => TRUE,
   );

   return system_settings_form($form);
 }


function timelinejs_menu() {

  $items = array();

  $items['admin/config/services/timelinejs'] = array(
    'title' => 'Timelinejs module settings',
    'description' => t('Settings for your timeline'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('timelinejs_admin'),
    'access arguments' => array('administer timelinejs settings'),
    'type' => MENU_NORMAL_ITEM,
   );

  return $items;
}

drupal_add_js(array('timelinejs' => array(
  'timelineSource' => 'https://docs.google.com/spreadsheet/pub?key=0AlNyK0CWPkZjdE82U1dQNkRKRHdDaldmZUlnZUlBX0E&output=htmlt',
  'embedSource' => "<script type='text/javascript' src='http://workvm/aboutblank/sites/all/modules/custom/timelinejs/TimelineJS/compiled/js/storyjs-embed.js'></script>",
  )), array('type' => 'setting', 'weight' => 10));

drupal_add_js(base_path()."sites/all/modules/custom/timelinejs/timeline_embed.js", array('type' => 'file', 'weight' => 0));



